CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_ID_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'id_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'PII'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.ID_REC a;
 
 CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_PROFILE_REC AS 
    SELECT p.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'prof_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'PII'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.PROFILE_REC p;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_ADM_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'adm_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Admissions' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.ADM_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_PROG_ENR_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'prog_enr_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.PROG_ENR_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_STU_ACAD_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'stu_acad_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.STU_ACAD_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_STUSTAT_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'stu_stat_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.STU_STAT_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_CW_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'cw_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.CW_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_CRS_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'crs_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.CRS_REC a;
    
    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_SEC_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'sec_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.SEC_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_MTG_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'mtg_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.MTG_REC a;
    
    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_FAC_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'fac_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.FAC_REC a;
    

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_SBCUST_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'sbcust_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Bursar' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.SBCUST_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_STU_SERV_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'stu_serv__rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.STU_SERV_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_SUBA_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'suba_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Financial' AS META_DATA_OWNER,
    'Internal'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.SUBA_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_GRD_TABLE AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'grd_table' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.GRD_TABLE a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_ACAD_CAL_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'acad_cal_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.ACAD_CAL_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_MAJOR_TABLE AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'major_table' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.MAJOR_TABLE a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_DEG_TABLE AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'acad_cal_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.DEG_TABLE a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_DEPT_TABLE AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'dept_table' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.DEPT_TABLE a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_REG_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'reg_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Student' AS META_DATA_OWNER,
    'Restricted'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.REG_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_CTC_REC AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'ctc_rec' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Restricted'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.CTC_REC a;

    CREATE OR REPLACE TABLE DITTEAU_DATA.SILVER.SILVER_CX_CTC_TABLE AS 
    SELECT a.*,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'JENZABAR CX' AS META_SOURCE_SYSTEM,
    'ctc_table' AS META_SOURCE_FILE,
    '001' AS META_BATCH_ID,
    'TRUE' AS META_LOAD_STAT,
    'SNOWFLAKE DATASHARE' AS META_INGEST_TYPE,
    'Common' AS META_DATA_OWNER,
    'Public'AS META_DATA_CLASS
    FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.CTC_TABLE a;
