-- Use SECURITYADMIN role for role and user management
USE ROLE SECURITYADMIN;

-- Create Functional Roles
CREATE ROLE IF NOT EXISTS DITTEAU_DATA_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS ENROLLMENT_ANALYST;
CREATE ROLE IF NOT EXISTS IR_ANALYST;
CREATE ROLE IF NOT EXISTS GOVERNANCE_ADMIN;

-- Create Hierarchy (Grant roles to other roles)
GRANT ROLE DATA_ENGINEER TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE DATA_ANALYST TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE ENROLLMENT_ANALYST TO ROLE DATA_ANALYST;
GRANT ROLE FIN_AID_ANALYST TO ROLE DATA_ANALYST; 

-- Grant specific administration roles

GRANT ROLE DITTEAU_DATA_ADMIN TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE_ADMIN TO ROLE SECURITYADMIN;

-- Grant Privileges to Roles

-- DITTEAU_DATA_ADMIN (High-level admin for the database)
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE DITTEAU_DATA TO ROLE DITTEAU_DATA_ADMIN;
-- ... and other object types as needed (streams, tasks, pipes, stages, etc.)

-- DATA_ENGINEER (Can build and transform data)
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA SILVER TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GOLD TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GOVERNANCE TO ROLE DATA_ENGINEER; -- Needs to see policies to apply them

GRANT CREATE TABLE ON SCHEMA BRONZE TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA SILVER TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA GOLD TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GOLD TO ROLE DATA_ENGINEER;
-- Future grants for new objects
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE DATA_ENGINEER;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA SILVER TO ROLE DATA_ENGINEER;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE DATA_ENGINEER;


-- DATA_ANALYST (Reads from Gold, sometimes Silver)
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA GOLD TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA SILVER TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA GOVERNANCE TO ROLE DATA_ANALYST; -- Needs to be able to evaluate policies

GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER TO ROLE DATA_ANALYST; -- ad-hoc Silver access is allowed
GRANT SELECT ON ALL VIEWS IN SCHEMA SILVER TO ROLE DATA_ANALYST;
-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SILVER TO ROLE DATA_ANALYST;

-- ENROLLMENT_ANALYST (Specific access, example for row-level policy later)
GRANT ROLE DATA_ANALYST TO ROLE ENROLLMENT_ANALYST; -- Inherits all DATA_ANALYST permissions
-- We'll apply policies to restrict data further for this role

-- FINANCIAL_AID_OFFICE (Needs conditional access to sensitive data)
GRANT ROLE DATA_ANALYST TO ROLE IR_ANALYST; -- Inherits DATA_ANALYST permissions
-- Policies will grant specific access to SSN/PII under certain conditions

-- GOVERNANCE_ADMIN (Manages policies)
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE GOVERNANCE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DITTEAU_DATA.GOVERNANCE TO ROLE GOVERNANCE_ADMIN;
GRANT CREATE MASKING POLICY ON SCHEMA DITTEAU_DATA.GOVERNANCE TO ROLE GOVERNANCE_ADMIN;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA DITTEAU_DATA.GOVERNANCE TO ROLE GOVERNANCE_ADMIN;

-- Needs USAGE on other schemas to APPLY policies
GRANT USAGE ON SCHEMA BRONZE TO ROLE GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA SILVER TO ROLE GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOLD TO ROLE GOVERNANCE_ADMIN;

-- Assign Roles to Users

-- GRANT ROLE DATA_ENGINEER TO USER 'lvanpelt';
-- GRANT ROLE DATA_ANALYST TO USER 'jane_doe';
-- GRANT ROLE IR_ANALYST TO USER 'fred_smith';
-- GRANT ROLE GOVERNANCE_ADMIN TO USER 'admin_user';