USE ROLE GOVERNANCE_ADMIN;
USE DATABASE DITTEAU_DATA;
USE SCHEMA GOVERNANCE;

CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE.STUDENT_ENROLLMENT_ROW_ACCESS_POLICY
ON (ENROLLMENT_STATUS VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'DITTEAU_DATA_ADMIN' THEN TRUE -- Admins see all
        WHEN CURRENT_ROLE() = 'ENROLLMENT_ANALYST' THEN ENROLLMENT_STATUS = 'Enrolled'
        WHEN CURRENT_ROLE() = 'IR_ANALYST' THEN ENROLLMENT_STATUS IN ('Enrolled', 'Leave of Absence')
        ELSE ENROLLMENT_STATUS = 'Enrolled' -- Default for others (e.g., DATA_ANALYST)
    END;