USE ROLE DITTEAU_DATA_ADMIN;
USE DATABASE DITTEAU_DATA;
USE SCHEMA GOLD;

ALTER TABLE GOLD.DIM_INTEGRATION_IDS MODIFY COLUMN SSN SET TAG GOVERNANCE.CONFIDENTIAL = 'TRUE';
ALTER TABLE GOLD.FACT_FINANCIAL_AID_AWARDS MODIFY COLUMN AWARD_AMOUNT_OFFERED  SET TAG GOVERNANCE.FINANCIAL_DATA = 'TRUE';
ALTER TABLE GOLD.DIM_STUDENT MODIFY COLUMN STUDENT_DOB SET TAG GOVERNANCE.STUDENT_DEMOGRAPHICS = 'TRUE';

