-- STEP 1: Insert from DIM_STUDENT + CX + PowerFAIDS
INSERT INTO DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS (
    STUDENT_UNIVERSAL_ID,
    DD_STUDENT_ID,
    CX_STUDENT_ID,
    POWERFAIDS_STUDENT_ID,
    SSN,
    IS_ACTIVE,
    CREATION_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP
)
SELECT
    UUID_STRING() AS STUDENT_UNIVERSAL_ID,
    s.STUDENT_KEY AS DD_STUDENT_ID,
    cx.id AS CX_STUDENT_ID,
    pf.STUDENT_ID AS POWERFAIDS_STUDENT_ID,
    cx.SS_NO AS SSN,
    TRUE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.GOLD.DIM_STUDENT s
LEFT JOIN DITTEAU_DATA.SILVER.SILVER_CX_ID_REC cx
    ON s.STUDENT_CODE = cx.id
LEFT JOIN DITTEAU_DATA.SILVER.SILVER_PF_APPLICATIONS pf
    ON s.STUDENT_CODE = pf.SIS_ID
LEFT JOIN DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS existing
    ON s.STUDENT_KEY = existing.DD_STUDENT_ID
WHERE existing.DD_STUDENT_ID IS NULL;
