-- UPDATE existing with new PF data
UPDATE DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS tgt
SET POWERFAIDS_STUDENT_ID = pf.STUDENT_ID,
    SSN = pf.SSN,
    LAST_UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_PF_APPLICATIONS pf
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s
    ON pf.SIS_ID = s.STUDENT_CODE
WHERE tgt.DD_STUDENT_ID = s.STUDENT_KEY
  AND (tgt.POWERFAIDS_STUDENT_ID IS NULL OR tgt.SSN IS NULL);
