USE ROLE DITTEAU_DATA_ADMIN;
USE DATABASE DITTEAU_DATA;
USE SCHEMA GOLD;

ALTER TABLE GOLD.DIM_STUDENT MODIFY COLUMN MAJOR SET TAG GOVERNANCE.CONFIDENTIAL = 'TRUE';
ALTER TABLE GOLD.DIM_STUDENT MODIFY COLUMN GPA SET TAG GOVERNANCE.FINANCIAL_DATA = 'TRUE';
ALTER TABLE GOLD.DIM_STUDENT MODIFY COLUMN DATE_OF_BIRTH SET TAG GOVERNANCE.STUDENT_DEMOGRAPHICS = 'TRUE';

