CREATE OR REPLACE TABLE SILVER_PF_AWARDS AS
SELECT 
    TRY_TO_NUMBER(AWARD_AMOUNT_OFFERED) AS AWARD_AMOUNT_OFFERED,
    TRY_TO_NUMBER(AWARD_AMOUNT_ACCEPTED) AS AWARD_AMOUNT_ACCEPTED,
    TRY_TO_NUMBER(DISBURSEMENT_AMOUNT_1) AS DISBURSEMENT_AMOUNT_1,
    TRY_TO_NUMBER(DISBURSEMENT_AMOUNT_2) AS DISBURSEMENT_AMOUNT_2,
    TRY_TO_DATE(DISBURSEMENT_DATE) AS DISBURSEMENT_DATE,
    TRY_TO_DATE(DISBURSEMENT_DATE_SCHEDULED_2) AS DISBURSEMENT_DATE_SCHEDULED_2,
    TRY_TO_DATE(CREATION_DATE) AS CREATION_DATE,
    TRY_TO_DATE(LAST_UPDATE_DATE) AS LAST_UPDATE_DATE,
    STUDENT_ID,
    AWARD_YEAR,
    AWARD_CODE,
    AWARD_DESCRIPTION,
    AWARD_TYPE,
    AWARD_STATUS,
    DISBURSEMENT_STATUS,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'PowerFAIDS' AS META_SOURCE_SYSTEM,
    'Bronze Layer' AS META_SOURCE_FILE,
    NULL AS META_BATCH_ID,
    'SUCCESS' AS META_LOAD_STAT,
    'FULL' AS META_INGEST_TYPE,
    'Financial Aid Office' AS META_DATA_OWNER,
    'Confidential' AS META_DATA_CLASS
FROM DITTEAU_DATA.BRONZE.BRONZE_PF_AWARDS;

-- SILVER_PF_APPLICATIONS
CREATE OR REPLACE TABLE SILVER_PF_APPLICATIONS AS
SELECT
    STUDENT_ID,
    APPLICATION_YEAR,
    APPLICATION_TYPE,
    EFC,
    DEPENDENCY_STATUS,
    FAFSA_RECEIVED_DATE,
    FAFSA_VERIFICATION_STATUS,
    INCOME_STUDENT,
    INCOME_PARENTS,
    HOUSEHOLD_SIZE,
    NUMBER_IN_COLLEGE,
    APPLICATION_STATUS,
    ISIR_TRANSACTION_ID,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'PowerFAIDS' AS META_SOURCE_SYSTEM,
    'Bronze Layer' AS META_SOURCE_FILE,
    NULL AS META_BATCH_ID,
    'SUCCESS' AS META_LOAD_STAT,
    'FULL' AS META_INGEST_TYPE,
    'Financial Aid Office' AS META_DATA_OWNER,
    'Confidential' AS META_DATA_CLASS
FROM DITTEAU_DATA.BRONZE.BRONZE_PF_APPLICATIONS;

-- SILVER_PF_REQUIREMENTS
CREATE OR REPLACE TABLE SILVER_PF_REQUIREMENTS AS
SELECT
    STUDENT_ID,
    AID_YEAR,
    REQUIREMENT_CODE,
    REQUIREMENT_DESCRIPTION,
    STATUS,
    TRY_TO_DATE(DATE_ASSIGNED) AS DATE_ASSIGNED,
    TRY_TO_DATE(DATE_SATISFIED) AS DATE_SATISFIED,
    LAST_MODIFIED_USER,
    CURRENT_TIMESTAMP() AS META_INGEST_TS,
    'PowerFAIDS' AS META_SOURCE_SYSTEM,
    'Bronze Layer' AS META_SOURCE_FILE,
    NULL AS META_BATCH_ID,
    'SUCCESS' AS META_LOAD_STAT,
    'FULL' AS META_INGEST_TYPE,
    'Financial Aid Office' AS META_DATA_OWNER,
    'Confidential' AS META_DATA_CLASS
FROM DITTEAU_DATA.BRONZE.BRONZE_PF_REQUIREMENTS;