SELECT
    T.TERM_ACAD_YR AS academic_year,
    F.FACULTY_FIRSTNAME || ' ' || F.FACULTY_LASTNAME AS faculty_name,
    M.MAJOR_DESCR AS major,
    -- Extracts the first digit of the course number to determine the level (e.g., 1 for 100-level, 2 for 200-level)
    LEFT(C.COURSE_SECTION_COURSE_NUMBER, 1) || '00' AS course_level,
    -- Calculates the average grade points. We only consider grades with points to exclude non-graded entries.
    AVG(G.GRADE_PTS) AS average_grade_points
FROM
    DITTEAU_DATA.GOLD.FACT_ENROLLMENT AS E
JOIN
    DITTEAU_DATA.GOLD.DIM_FACULTY AS F ON E.ENROLLMENT_FACULTY_KEY = F.FACULTY_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_GRADE AS G ON E.ENROLLMENT_GRADE_KEY = G.GRADE_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_TERM AS T ON E.ENROLLMENT_TERM_KEY = T.TERM_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_STUDENT AS S ON E.ENROLLMENT_STU_KEY = S.STUDENT_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_MAJOR AS M ON S.STUDENT_MAJOR = M.MAJOR_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_COURSE_SECTION AS C ON E.ENROLLMENT_COURSE_SECTION_KEY = C.COURSE_SECTION_KEY
WHERE
G.GRADE_PTS IS NOT NULL
GROUP BY
    academic_year,
    faculty_name,
    major,
    course_level
ORDER BY
    academic_year,
    faculty_name,
    course_level,
    major;

-- Average Grades Over Time by Department or Major
SELECT 
    t.TERM_YEAR,
    t.TERM_SESS,
    'Department' AS CATEGORY_TYPE,
    d.DEPT_DESCR AS CATEGORY_NAME,
    AVG(g.GRADE_PTS) AS AVG_GRADE_POINTS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s 
    ON f.ENROLLMENT_STU_KEY = s.STUDENT_KEY
JOIN DITTEAU_DATA.GOLD.DIM_COURSE_SECTION cs 
    ON f.ENROLLMENT_COURSE_SECTION_KEY = cs.COURSE_SECTION_KEY
JOIN DITTEAU_DATA.GOLD.DIM_DEPT d
    ON cs.COURSE_SECTION_DEPT = d.DEPT_CODE
JOIN DITTEAU_DATA.GOLD.DIM_GRADE g 
    ON f.ENROLLMENT_GRADE_KEY = g.GRADE_KEY
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE g.GRADE_PTS IS NOT NULL
GROUP BY t.TERM_YEAR, t.TERM_SESS, d.DEPT_DESCR

UNION ALL

SELECT 
    t.TERM_YEAR,
    t.TERM_SESS,
    'Major' AS CATEGORY_TYPE,
    m.MAJOR_DESCR AS CATEGORY_NAME,
    AVG(g.GRADE_PTS) AS AVG_GRADE_POINTS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s 
    ON f.ENROLLMENT_STU_KEY = s.STUDENT_KEY
JOIN DITTEAU_DATA.GOLD.DIM_MAJOR m 
    ON s.STUDENT_MAJOR = m.MAJOR_KEY
JOIN DITTEAU_DATA.GOLD.DIM_GRADE g 
    ON f.ENROLLMENT_GRADE_KEY = g.GRADE_KEY
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE g.GRADE_PTS IS NOT NULL
GROUP BY t.TERM_YEAR, t.TERM_SESS, m.MAJOR_DESCR

ORDER BY TERM_YEAR, TERM_SESS, CATEGORY_TYPE, CATEGORY_NAME;



--Average Grades over time by dept
SELECT 
    t.TERM_YEAR,
    t.TERM_SESS,
    d.DEPT_DESCR AS DEPARTMENT,
    AVG(g.GRADE_PTS) AS AVG_GRADE_POINTS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s 
    ON f.ENROLLMENT_STU_KEY = s.STUDENT_KEY
JOIN DITTEAU_DATA.GOLD.DIM_COURSE_SECTION cs 
    ON f.ENROLLMENT_COURSE_SECTION_KEY = cs.COURSE_SECTION_KEY
JOIN DITTEAU_DATA.GOLD.DIM_DEPT d
    ON cs.COURSE_SECTION_DEPT = d.DEPT_CODE
JOIN DITTEAU_DATA.GOLD.DIM_GRADE g 
    ON f.ENROLLMENT_GRADE_KEY = g.GRADE_KEY
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE g.GRADE_PTS IS NOT NULL
GROUP BY t.TERM_YEAR, t.TERM_SESS, d.DEPT_DESCR
ORDER BY t.TERM_YEAR, t.TERM_SESS, d.DEPT_DESCR;


SELECT 
    t.TERM_ACAD_YR,
    d.DEPT_DESCR,
    AVG(f.ENROLLMENT_HOURS) AS AVG_CREDIT_HOURS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_COURSE_SECTION cs 
    ON f.ENROLLMENT_COURSE_SECTION_KEY = cs.COURSE_SECTION_KEY
JOIN DITTEAU_DATA.GOLD.DIM_DEPT d 
    ON cs.COURSE_SECTION_DEPT = d.DEPT_CODE
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE f.IS_CURRENT = 'TRUE'
GROUP BY t.TERM_ACAD_YR, d.DEPT_DESCR
ORDER BY t.TERM_ACAD_YR, d.DEPT_DESCR;


SELECT 
    t.TERM_ACAD_YR,
    m.MAJOR_DESCR,
    AVG(g.GRADE_PTS) AS AVG_GRADE_POINTS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s 
    ON f.ENROLLMENT_STU_KEY = s.STUDENT_KEY
JOIN DITTEAU_DATA.GOLD.DIM_MAJOR m 
    ON s.STUDENT_MAJOR = m.MAJOR_KEY
JOIN DITTEAU_DATA.GOLD.DIM_GRADE g 
    ON f.ENROLLMENT_GRADE_KEY = g.GRADE_KEY
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE f.IS_CURRENT = 'TRUE'
GROUP BY t.TERM_ACAD_YR, m.MAJOR_DESCR
ORDER BY t.TERM_ACAD_YR, m.MAJOR_DESCR;

--Department and Major Cross Analysis (Av GPA and Hours)
SELECT 
    t.TERM_ACAD_YR,
    d.DEPT_DESCR,
    m.MAJOR_DESCR,
    AVG(f.ENROLLMENT_HOURS) AS AVG_CREDIT_HOURS,
    AVG(g.GRADE_PTS) AS AVG_GPA_POINTS
FROM DITTEAU_DATA.GOLD.FACT_ENROLLMENT f
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s 
    ON f.ENROLLMENT_STU_KEY = s.STUDENT_KEY
JOIN DITTEAU_DATA.GOLD.DIM_MAJOR m 
    ON s.STUDENT_MAJOR = m.MAJOR_KEY
JOIN DITTEAU_DATA.GOLD.DIM_COURSE_SECTION cs 
    ON f.ENROLLMENT_COURSE_SECTION_KEY = cs.COURSE_SECTION_KEY
JOIN DITTEAU_DATA.GOLD.DIM_DEPT d 
    ON cs.COURSE_SECTION_DEPT = d.DEPT_CODE
JOIN DITTEAU_DATA.GOLD.DIM_GRADE g 
    ON f.ENROLLMENT_GRADE_KEY = g.GRADE_KEY
JOIN DITTEAU_DATA.GOLD.DIM_TERM t 
    ON f.ENROLLMENT_TERM_KEY = t.TERM_KEY
WHERE f.IS_CURRENT = 'TRUE'
GROUP BY t.TERM_ACAD_YR, d.DEPT_DESCR, m.MAJOR_DESCR
ORDER BY t.TERM_ACAD_YR, d.DEPT_DESCR, m.MAJOR_DESCR;
