--DW Query
SELECT
    T.TERM_ACAD_YR AS academic_year,
    D.DEPT_DESCR AS department,
    M.MAJOR_DESCR AS major,
    substring(C.COURSE_SECTION_COURSE_NUMBER, 4,1) || '00' AS course_level,
    SUM(G.GRADE_PTS * E.ENROLLMENT_HOURS) 
        / NULLIF(SUM(E.ENROLLMENT_HOURS), 0) AS average_grade_points
FROM
    DITTEAU_DATA.GOLD.FACT_ENROLLMENT AS E
JOIN
    DITTEAU_DATA.GOLD.DIM_FACULTY AS F ON E.ENROLLMENT_FACULTY_KEY = F.FACULTY_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_GRADE AS G ON E.ENROLLMENT_GRADE_KEY = G.GRADE_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_TERM AS T ON E.ENROLLMENT_TERM_KEY = T.TERM_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_STUDENT AS S ON E.ENROLLMENT_STU_KEY = S.STUDENT_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_MAJOR AS M ON S.STUDENT_MAJOR = M.MAJOR_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_COURSE_SECTION AS C ON E.ENROLLMENT_COURSE_SECTION_KEY = C.COURSE_SECTION_KEY
JOIN
    DITTEAU_DATA.GOLD.DIM_DEPT AS D ON F.FACULTY_DEPT = D.DEPT_KEY
WHERE
  G.GRADE_PTS IS NOT NULL
    AND E.ENROLLMENT_HOURS IS NOT NULL
GROUP BY
    department,
    academic_year,
    major,
    course_level
ORDER BY
    department,
    academic_year,
    course_level,
    major;

--Query from silver, transactional

SELECT
    A.ACYR AS academic_year,
    D.TXT AS department,
    M.TXT AS major, 
    SUBSTRING(C.CRS_NO, 4, 1) || '00' AS course_level, 
    SUM(G.PTS * CW.HRS) / NULLIF(SUM(CW.HRS), 0) AS average_grade_points
FROM
    DITTEAU_DATA.SILVER.SILVER_CX_CW_REC CW
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_CRS_REC C 
        ON CW.CRS_NO = C.CRS_NO 
       AND CW.CAT = C.CAT
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_SEC_REC S
        ON CW.CRS_NO = S.CRS_NO 
       AND CW.CAT = S.CAT
       AND CW.SEC = S.SEC_NO
       AND CW.SESS = S.SESS
       AND CW.YR = S.YR
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_GRD_TABLE G 
        ON CW.GRD = G.GRD
        AND CW.GRDG = G.CTGRY
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_ACAD_CAL_REC A 
        ON CW.YR = A.YR 
       AND CW.SESS = A.SESS
       AND CW.PROG = A.PROG
       AND CW.SUBSESS = A.SUBSESS
JOIN 
    DITTEAU_DATA.SILVER.SILVER_CX_FAC_REC F 
        ON S.FAC_ID = F.ID
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_DEPT_TABLE D 
        ON F.DEPT = D.DEPT
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_PROG_ENR_REC P 
        ON CW.ID = P.ID 
       AND CW.PROG = P.PROG  
JOIN
    DITTEAU_DATA.SILVER.SILVER_CX_MAJOR_TABLE M
        ON P.MAJOR1 = M.MAJOR       
WHERE
    G.PTS IS NOT NULL
    AND CW.HRS IS NOT NULL
GROUP BY
    D.TXT,
    A.ACYR,
    M.TXT,
    SUBSTRING(C.CRS_NO, 4, 1) || '00'
ORDER BY
    department,
    academic_year,
    course_level,
    major;
