USE DATABASE DITTEAU_DATA;
USE SCHEMA BRONZE;

-- Bronze table for Awards Data
CREATE OR REPLACE TABLE BRONZE.POWERFAIDS_AWARDS_RAW (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(255),
    FILE_ROW_NUMBER NUMBER
);

-- Ingest into awards table
COPY INTO BRONZE.POWERFAIDS_AWARDS_RAW (RAW_DATA, FILE_NAME, FILE_ROW_NUMBER)
FROM (
    SELECT
        ARRAY_CONSTRUCT_COMPACT( -- Constructs an array from all input columns
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
        ),
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @RAW_POWERFAIDS_STAGE/powerfaids_awards.csv.gz
)
FILE_FORMAT = (TYPE = CSV
               FIELD_DELIMITER = ','
               RECORD_DELIMITER = '\n'
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               NULL_IF = ('', 'NULL', 'null')
              )
ON_ERROR = 'CONTINUE' -- Continue if some rows fail, log errors
PURGE = FALSE; -- Set to TRUE if you want to delete files from stage after successful copy

-- Bronze table for Applications Data
CREATE OR REPLACE TABLE BRONZE.POWERFAIDS_APPLICATIONS_RAW (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(255),
    FILE_ROW_NUMBER NUMBER
);

-- Ingest into applications table
COPY INTO BRONZE.POWERFAIDS_APPLICATIONS_RAW (RAW_DATA, FILE_NAME, FILE_ROW_NUMBER)
FROM (
    SELECT
        $1 AS RAW_DATA,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @RAW_POWERFAIDS_STAGE/powerfaids_applications.csv
)
FILE_FORMAT = (TYPE = CSV
               FIELD_DELIMITER = NONE
               RECORD_DELIMITER = '\n'
               SKIP_HEADER = 1
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
              )
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

-- Bronze table for Requirements/Holds Data
CREATE OR REPLACE TABLE BRONZE.POWERFAIDS_REQUIREMENTS_RAW (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(255),
    FILE_ROW_NUMBER NUMBER
);

-- Ingest into requirements table
COPY INTO BRONZE.POWERFAIDS_REQUIREMENTS_RAW (RAW_DATA, FILE_NAME, FILE_ROW_NUMBER)
FROM (
    SELECT
        $1 AS RAW_DATA,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @RAW_POWERFAIDS_STAGE/powerfaids_requirements.csv
)
FILE_FORMAT = (TYPE = CSV
               FIELD_DELIMITER = NONE
               RECORD_DELIMITER = '\n'
               SKIP_HEADER = 1
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
              )
ON_ERROR = 'CONTINUE'
PURGE = FALSE;


-- Verify ingestion (using sample size to see raw data)
SELECT RAW_DATA, FILE_NAME, FILE_ROW_NUMBER FROM BRONZE.POWERFAIDS_AWARDS_RAW LIMIT 5;
SELECT RAW_DATA, FILE_NAME, FILE_ROW_NUMBER FROM BRONZE.POWERFAIDS_APPLICATIONS_RAW LIMIT 5;
SELECT RAW_DATA, FILE_NAME, FILE_ROW_NUMBER FROM BRONZE.POWERFAIDS_REQUIREMENTS_RAW LIMIT 5;