CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.FACT_FINANCIAL_AID_AWARDS (
    FIN_AID_AWARD_KEY INT AUTOINCREMENT PRIMARY KEY,

    -- Dimension Keys
    FIN_AID_STU_KEY INT,
    FIN_AID_IDENTITY_KEY INT,
    FIN_AID_TERM_KEY INT,
    DIM_AWARD_KEY INT,
    -- Award Data
    FIN_AID_AWARD_STATUS INT,
    FIN_AID_DISBURSEMENT_STATUS INT,
    AWARD_AMOUNT_OFFERED NUMBER(10,2),
    AWARD_AMOUNT_ACCEPTED NUMBER(10,2),
    TOTAL_DISBURSED_AMOUNT NUMBER(10,2),

    -- Date Keys from DIM_DATE
    DISBURSEMENT_DATE_1_KEY NUMBER(8,0),
    DISBURSEMENT_DATE_2_KEY NUMBER(8,0),

    -- SCD Tracking
    IS_CURRENT STRING,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    CREATION_TIMESTAMP TIMESTAMP_LTZ,
    LAST_UPDATED_TIMESTAMP TIMESTAMP_LTZ,

    -- Foreign Keys
    FOREIGN KEY (FIN_AID_STU_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_STUDENT(STUDENT_KEY),
    FOREIGN KEY (FIN_AID_IDENTITY_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS(IDENTITY_KEY),
    FOREIGN KEY (FIN_AID_TERM_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_TERM(TERM_KEY),
    FOREIGN KEY (DIM_AWARD_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_AWARDS(AWARD_KEY),
    FOREIGN KEY (DISBURSEMENT_DATE_1_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_DATE(DATE_KEY),
    FOREIGN KEY (DISBURSEMENT_DATE_2_KEY) REFERENCES DITTEAU_DATA.GOLD.DIM_DATE(DATE_KEY)
);

INSERT INTO DITTEAU_DATA.GOLD.FACT_FINANCIAL_AID_AWARDS (
    FIN_AID_STU_KEY,
    FIN_AID_IDENTITY_KEY,
    FIN_AID_TERM_KEY,
    DIM_AWARD_KEY,
    AWARD_AMOUNT_OFFERED,
    AWARD_AMOUNT_ACCEPTED,
    TOTAL_DISBURSED_AMOUNT,
    DISBURSEMENT_DATE_1_KEY,
    DISBURSEMENT_DATE_2_KEY,
    IS_CURRENT,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    CREATION_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP
)
SELECT
    s.STUDENT_KEY,
    i.IDENTITY_KEY,
    t.TERM_KEY,
    a.AWARD_KEY,
    p.AWARD_AMOUNT_OFFERED,
    p.AWARD_AMOUNT_ACCEPTED,
    COALESCE(p.DISBURSEMENT_AMOUNT_1,0) + COALESCE(p.DISBURSEMENT_AMOUNT_2,0),
    d1.DATE_KEY,
    d2.DATE_KEY,
    'Y',
    p.CREATION_DATE,
    '9999-12-31',
    CURRENT_TIMESTAMP(),
    p.LAST_UPDATE_DATE
FROM DITTEAU_DATA.SILVER.SILVER_PF_AWARDS p
JOIN DITTEAU_DATA.GOLD.DIM_AWARDS a
    ON a.AWARD_CODE = p.award_code
JOIN DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS i
    ON p.STUDENT_ID = i.POWERFAIDS_STUDENT_ID
JOIN DITTEAU_DATA.GOLD.DIM_STUDENT s
    ON s.STUDENT_KEY = i.DD_STUDENT_ID
LEFT JOIN DITTEAU_DATA.GOLD.DIM_TERM t
    ON p.AWARD_YEAR = t.TERM_YEAR
LEFT JOIN DITTEAU_DATA.GOLD.DIM_DATE d1
    ON p.DISBURSEMENT_DATE = d1.DATE_ACTUAL
LEFT JOIN DITTEAU_DATA.GOLD.DIM_DATE d2
    ON p.DISBURSEMENT_DATE_SCHEDULED_2 = d2.DATE_ACTUAL;
