CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_AWARDS (
    AWARD_KEY INT AUTOINCREMENT PRIMARY KEY,
    AWARD_CODE VARCHAR,
    AWARD_DESCR VARCHAR,
    AWARD_TYPE VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_AWARDS (
    AWARD_CODE,
    AWARD_DESCR,
    AWARD_TYPE,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT distinct
    a.AWARD_CODE,
    a.AWARD_DESCRIPTION,
    a.award_type,
    '01/01/1900',
    '12/31/2999',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_PF_AWARDS a;