CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_INTEGRATION_IDS (
    IDENTITY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STUDENT_UNIVERSAL_ID VARCHAR,               -- canonical ID
    DD_STUDENT_ID VARCHAR,                  -- ditteau data from dim_student
    CX_STUDENT_ID VARCHAR,                  -- Jenzabar CX
    POWERFAIDS_STUDENT_ID VARCHAR,              -- PowerFAIDS
    WORKDAY_STUDENT_ID VARCHAR,            -- Workday
    SSN VARCHAR,                             --Social Security Number
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATION_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED_TIMESTAMP TIMESTAMP_LTZ
);
