--Create the Degree Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_DEGREE (
    DEGREE_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEGREE_CODE VARCHAR,
    DEGREE_DESCR VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_DEGREE (
    DEGREE_CODE,
    DEGREE_DESCR,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.deg,
    a.txt,
    a.active_date,
    a.inactive_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_DEG_TABLE a;


--Create the Major Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_MAJOR (
    MAJOR_KEY INT AUTOINCREMENT PRIMARY KEY,
    MAJOR_CODE VARCHAR,
    MAJOR_DESCR VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_MAJOR (
    MAJOR_CODE,
    MAJOR_DESCR,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.major,
    a.txt,
    a.active_date,
    a.inactive_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_MAJOR_TABLE a;

--Create the Ethnicity Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_ETHNICITY (
    ETHNICITY_KEY INT AUTOINCREMENT PRIMARY KEY,
    ETHNICITY_CODE VARCHAR,
    ETHNICITY_DESCR VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_ETHNICITY (
    ETHNICITY_CODE,
    ETHNICITY_DESCR,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.ethnic,
    a.txt,
    a.active_date,
    a.inactive_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.ETHNIC_TABLE a;

--Create the Grade Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_GRADE (
    GRADE_KEY INT AUTOINCREMENT PRIMARY KEY,
    GRADE_CODE VARCHAR,
    GRADE_DESCR VARCHAR,
    GRADE_CATEGORY VARCHAR,
    GRADE_PTS FLOAT,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_GRADE (
    GRADE_CODE,
    GRADE_DESCR,
    GRADE_CATEGORY,
    GRADE_PTS,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.grd,
    a.txt,
    a.ctgry,
    a.pts,
    a.active_date,
    a.inactive_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.GRD_TABLE a;

--Create the Course Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_COURSE (
    COURSE_KEY INT AUTOINCREMENT PRIMARY KEY,
    COURSE_CODE VARCHAR,
    COURSE_TITLE VARCHAR,
    COURSE_CATALOG VARCHAR,
    COURSE_PROGRAM_LEVEL VARCHAR,
    COURSE_DEPT VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT VARCHAR,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_COURSE (
    COURSE_CODE,
    COURSE_TITLE,
    COURSE_CATALOG,
    COURSE_PROGRAM_LEVEL,
    COURSE_DEPT,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.crs_no,
    a.title1 || a.title2 || a.title3,
    a.cat,
    a.prog,
    a.dept,
    a.stat_date,
    '9999-12-31',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_CRS_REC a;

--Create the Section Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_SECTION (
    SECTION_KEY INT AUTOINCREMENT PRIMARY KEY,
    SECTION_COURSE_KEY INT,
    SECTION_NUMBER VARCHAR,
    SECTION_TITLE VARCHAR,
    SECTION_CATALOG VARCHAR,
    SECTION_TERM_KEY INT,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT VARCHAR,
    CREATION_TIMESTAMP TIMESTAMP_LTZ,
    FOREIGN KEY (SECTION_COURSE_KEY) REFERENCES DIM_COURSE(COURSE_KEY),
    FOREIGN KEY (SECTION_TERM_KEY) REFERENCES DIM_TERM(TERM_KEY)
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_SECTION (
    SECTION_COURSE_KEY,
    SECTION_NUMBER,
    SECTION_TITLE,
    SECTION_CATALOG,
    SECTION_TERM_KEY,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    c.course_key,
    a.sec_no,
    a.title,
    a.cat,
    b.term_key,
    a.stat_date,
    '9999-12-31',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_SEC_REC a,
     DITTEAU_DATA.GOLD.DIM_TERM b,
     DITTEAU_DATA.GOLD.DIM_COURSE c
WHERE a.sess = b.term_sess and
      a.yr = b.term_year and
      a.subsess = b.term_subsess and
      a.crs_no = c.course_code and
      a.cat = c.course_catalog
     ;

--Create the Term Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_TERM (
    TERM_KEY INT AUTOINCREMENT PRIMARY KEY,
    TERM_CODE VARCHAR,
    TERM_DESCR VARCHAR,
    TERM_ACAD_YR VARCHAR,
    TERM_SESS VARCHAR,
    TERM_YEAR INT,
    TERM_SUBSESS VARCHAR,
    TERM_PROGRAM_LEVEL VARCHAR,
    TERM_AWARD_YR VARCHAR,
    TERM_FISCAL_YR VARCHAR,
    TERM_BEG_DATE DATE,
    TERM_END_DATE DATE,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_TERM (
    TERM_CODE,
    TERM_DESCR,
    TERM_ACAD_YR,
    TERM_SESS,
    TERM_YEAR,
    TERM_SUBSESS,
    TERM_PROGRAM_LEVEL,
    TERM_AWARD_YR,
    TERM_FISCAL_YR,
    TERM_BEG_DATE,
    TERM_END_DATE,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    trim(a.sess)|| trim(nvl(a.subsess,'-')) || a.yr || trim(a.prog),
    'TBD',
    a.acyr,
    a.sess,
    a.yr,
    a.subsess,
    a.prog,
    award,
    fiscal,
    a.beg_date,
    a.end_date,
    a.beg_date,
    '9999-12-31',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_ACAD_CAL_REC a;

--Create the Department Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_DEPT (
    DEPT_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEPT_CODE VARCHAR,
    DEPT_DESCR VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_DEPT (
    DEPT_CODE,
    DEPT_DESCR,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.dept,
    a.txt,
    a.active_date,
    a.inactive_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_DEPT_TABLE a;

--Create the Faculty Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_FACULTY (
    FACULTY_KEY INT AUTOINCREMENT PRIMARY KEY,
    FACULTY_CODE VARCHAR,
    FACULTY_LASTNAME VARCHAR,
    FACULTY_FIRSTNAME VARCHAR,
    FACULTY_MIDDLENAME VARCHAR,
    FACULTY_PREFIX VARCHAR,
    FACULTY_SUFFIX VARCHAR,
    FACULTY_RANK VARCHAR,
    FACULTY_DEPT INT,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ,
    FOREIGN KEY (FACULTY_DEPT) REFERENCES DIM_DEPT(DEPT_KEY)
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_FACULTY (
    FACULTY_CODE,
    FACULTY_LASTNAME,
    FACULTY_FIRSTNAME,
    FACULTY_MIDDLENAME,
    FACULTY_PREFIX,
    FACULTY_SUFFIX,
    FACULTY_RANK,
    FACULTY_DEPT,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.id,
    b.lastname,
    b.firstname,
    b.middlename,
    b.title,
    b.suffix,
    a.title,
    c.dept_key,
    a.stat_date,
    '9999-12-31',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_FAC_REC a,
     DITTEAU_DATA.SILVER.SILVER_CX_ID_REC b,
     DITTEAU_DATA.GOLD.DIM_DEPT c
WHERE a.id = b.id and
      a.dept = c.dept_code
      ;
     
--Create the Student Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_STUDENT (
    STUDENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    STUDENT_CODE VARCHAR,
    STUDENT_LASTNAME VARCHAR,
    STUDENT_FIRSTNAME VARCHAR,
    STUDENT_MIDDLENAME VARCHAR,
    STUDENT_PREFIX VARCHAR,
    STUDENT_SUFFIX VARCHAR,
    STUDENT_MAJOR INT,
    STUDENT_DOB DATE,
    STUDENT_ETHNICITY INT,
    STUDENT_GRAD_DATE DATE,
    STUDENT_ACAD_STAT VARCHAR,
    STUDENT_PROGRAM_LEVEL VARCHAR,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT STRING,
    CREATION_TIMESTAMP TIMESTAMP_LTZ,
    FOREIGN KEY (STUDENT_MAJOR) REFERENCES DIM_MAJOR(MAJOR_KEY),
    FOREIGN KEY (STUDENT_ETHNICITY) REFERENCES DIM_ETHNICITY(ETHNICITY_KEY)
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_STUDENT (
    STUDENT_CODE,
    STUDENT_LASTNAME,
    STUDENT_FIRSTNAME,
    STUDENT_MIDDLENAME,
    STUDENT_PREFIX,
    STUDENT_SUFFIX,
    STUDENT_MAJOR,
    STUDENT_DOB,
    STUDENT_ETHNICITY,
    STUDENT_GRAD_DATE,
    STUDENT_ACAD_STAT,
    STUDENT_PROGRAM_LEVEL,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    a.id,
    b.lastname,
    b.firstname,
    b.middlename,
    b.title,
    b.suffix,
    d.major_key,
    a.birth_date,
    f.ethnicity_key,
    c.deg_grant_date,
    e.txt,
    c.prog,
    b.add_date,
    '9999-12-31',
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_PROFILE_REC a,
     DITTEAU_DATA.SILVER.SILVER_CX_ID_REC b,
     DITTEAU_DATA.SILVER.SILVER_CX_PROG_ENR_REC c,
     DITTEAU_DATA.GOLD.DIM_MAJOR d,
     DITTEAU_DATA.GOLD.DIM_ETHNICITY f,
     ORGDATACLOUD$INTERNAL$DITTEAU_DEMO_CX_DATA.DITTEAU_ARCHIVE.ACAD_STAT_TABLE e,
WHERE a.id = b.id and
      c.id = b.id and
      c.major1 = d.major_code and
      c.acst = e.acst and
      f.ethnicity_code = a.ethnic_code
      ;
  
--Create the All Courses and Section Dimension Table

CREATE OR REPLACE TABLE DITTEAU_DATA.GOLD.DIM_COURSE_SECTION (
    COURSE_SECTION_KEY INT AUTOINCREMENT PRIMARY KEY,
    COURSE_SECTION_COURSE_NUMBER VARCHAR,
    COURSE_SECTION_SECTION_NUMBER VARCHAR,
    COURSE_TITLE VARCHAR,
    SECTION_TITLE VARCHAR,
    COURSE_SECTION_CATALOG VARCHAR,
    COURSE_SECTION_SESS VARCHAR,
    COURSE_SECTION_YEAR INT,
    COURSE_SECTION_SUBSESS VARCHAR,
    COURSE_SECTION_PROGRAM_LEVEL VARCHAR,
    COURSE_SECTION_REG_NUMBER INT,
    COURSE_SECTION_STATUS VARCHAR,
    COURSE_SECTION_FACULTY_KEY INT,
    SOURCE_ACTIVE_DATE DATE,
    SOURCE_INACTIVE_DATE DATE,
    IS_CURRENT VARCHAR,
    CREATION_TIMESTAMP TIMESTAMP_LTZ,
    FOREIGN KEY (COURSE_SECTION_FACULTY_KEY) REFERENCES GOLD.DIM_FACULTY(FACULTY_KEY)
);
INSERT INTO DITTEAU_DATA.GOLD.DIM_COURSE_SECTION (
    COURSE_SECTION_COURSE_NUMBER,
    COURSE_SECTION_SECTION_NUMBER,
    COURSE_TITLE,
    SECTION_TITLE,
    COURSE_SECTION_CATALOG,
    COURSE_SECTION_SESS,
    COURSE_SECTION_YEAR,
    COURSE_SECTION_SUBSESS,
    COURSE_SECTION_PROGRAM_LEVEL,
    COURSE_SECTION_REG_NUMBER,
    COURSE_SECTION_STATUS,
    COURSE_SECTION_FACULTY_KEY,
    SOURCE_ACTIVE_DATE,
    SOURCE_INACTIVE_DATE,
    IS_CURRENT,
    CREATION_TIMESTAMP
)
SELECT
    b.crs_no,
    b.sec_no,
    a.title1 || ' ' || a.title2 || ' ' || a.title3,
    b.title,
    b.cat,
    b.sess,
    b.yr,
    b.subsess,
    a.prog,
    b.reg_num,
    b.stat,
    c.faculty_key,
    b.beg_date,
    b.end_date,
    'Y',
    CURRENT_TIMESTAMP()
FROM DITTEAU_DATA.SILVER.SILVER_CX_CRS_REC a,
     DITTEAU_DATA.SILVER.SILVER_CX_SEC_REC b,
     DITTEAU_DATA.GOLD.DIM_FACULTY c

WHERE a.crs_no = b.crs_no and
      a.cat = b.cat and
      b.fac_id = c.faculty_code
     ;    
